#include "topology_graph.hpp"

#include <sstream>
#include <map>
#include <iomanip>
#include <fstream>
#include <cstdlib>
#include <array>
#include <memory>
#include <iostream>

namespace nixl_topo {

void TopologyGraph::add_physical_node(const PhysicalNode& node) {
    physical_nodes_.push_back(node);
}

void TopologyGraph::add_hidden_node(const HiddenNode& node) {
    hidden_nodes_.push_back(node);
}

void TopologyGraph::add_edge(const Edge& edge) {
    edges_.push_back(edge);
}

std::string TopologyGraph::to_adjacency_list() const {
    std::ostringstream oss;

    // Header
    oss << "# Topology Graph - Adjacency List Format\n";
    oss << "# Generated by nixl-topo-disc topology discovery\n";
    oss << "# Format: NODE_ID [PROPERTIES] -> NEIGHBOR_ID [EDGE_PROPERTIES], ...\n\n";

    // Build adjacency map: node_id -> list of (neighbor_id, edge)
    std::map<std::string, std::vector<std::pair<std::string, const Edge*>>> adjacency;

    for (const auto& edge : edges_) {
        std::string src = edge.src_is_hidden
            ? "H" + std::to_string(edge.src_id)
            : "P" + std::to_string(edge.src_id);
        std::string dst = edge.dst_is_hidden
            ? "H" + std::to_string(edge.dst_id)
            : "P" + std::to_string(edge.dst_id);
        adjacency[src].push_back({dst, &edge});
    }

    // Output physical nodes
    oss << "# Physical Nodes\n";
    for (const auto& node : physical_nodes_) {
        std::string node_id = "P" + std::to_string(node.node_id);
        oss << node_id << " [tier=" << node.tier
            << ", cluster=" << node.cluster_id
            << ", type=" << to_string(node.type);
        if (!node.hostname.empty()) {
            oss << ", hostname=" << node.hostname;
        }
        oss << "]";

        auto it = adjacency.find(node_id);
        if (it != adjacency.end() && !it->second.empty()) {
            oss << " -> ";
            for (size_t i = 0; i < it->second.size(); ++i) {
                if (i > 0) oss << ", ";
                const auto& [dst, edge] = it->second[i];
                oss << dst << " [latency_ns=" << edge->latency_ns;
                if (edge->bandwidth_gbps > 0) {
                    oss << ", bw_gbps=" << std::fixed << std::setprecision(1)
                        << edge->bandwidth_gbps;
                }
                oss << "]";
            }
        }
        oss << "\n";
    }

    // Output hidden nodes
    if (!hidden_nodes_.empty()) {
        oss << "\n# Hidden Nodes\n";
        for (const auto& node : hidden_nodes_) {
            std::string node_id = "H" + std::to_string(node.hv_id);
            oss << node_id << " [tier=" << node.tier
                << ", type=" << to_string(node.type);
            if (!node.inferred_label.empty()) {
                oss << ", label=\"" << node.inferred_label << "\"";
            }
            oss << ", confidence=" << std::fixed << std::setprecision(2)
                << node.confidence << "]";

            auto it = adjacency.find(node_id);
            if (it != adjacency.end() && !it->second.empty()) {
                oss << " -> ";
                for (size_t i = 0; i < it->second.size(); ++i) {
                    if (i > 0) oss << ", ";
                    const auto& [dst, edge] = it->second[i];
                    oss << dst << " [latency_ns=" << edge->latency_ns;
                    if (edge->bandwidth_gbps > 0) {
                        oss << ", bw_gbps=" << std::fixed << std::setprecision(1)
                            << edge->bandwidth_gbps;
                    }
                    oss << "]";
                }
            }
            oss << "\n";
        }
    }

    return oss.str();
}

std::string TopologyGraph::to_dot() const {
    std::ostringstream oss;

    oss << "digraph topology {\n";
    oss << "    rankdir=TB;\n";
    oss << "    node [fontname=\"Helvetica\"];\n";
    oss << "    edge [fontname=\"Helvetica\", fontsize=10];\n\n";

    // Define physical nodes (boxes)
    oss << "    // Physical Nodes\n";
    for (const auto& node : physical_nodes_) {
        oss << "    P" << node.node_id << " [shape=box, label=\""
            << "P" << node.node_id;
        if (!node.hostname.empty()) {
            oss << "\\n" << node.hostname;
        }
        oss << "\\nTier " << node.tier << "\"];\n";
    }

    // Define hidden nodes (diamonds)
    if (!hidden_nodes_.empty()) {
        oss << "\n    // Hidden Nodes\n";
        for (const auto& node : hidden_nodes_) {
            oss << "    H" << node.hv_id << " [shape=diamond, style=filled, "
                << "fillcolor=lightgray, label=\"";
            if (!node.inferred_label.empty()) {
                oss << node.inferred_label;
            } else {
                oss << to_string(node.type) << "-" << node.hv_id;
            }
            oss << "\\nTier " << node.tier << "\"];\n";
        }
    }

    // Define edges
    oss << "\n    // Edges\n";
    for (const auto& edge : edges_) {
        std::string src = edge.src_is_hidden
            ? "H" + std::to_string(edge.src_id)
            : "P" + std::to_string(edge.src_id);
        std::string dst = edge.dst_is_hidden
            ? "H" + std::to_string(edge.dst_id)
            : "P" + std::to_string(edge.dst_id);

        oss << "    " << src << " -> " << dst << " [label=\""
            << edge.latency_ns << "ns\"];\n";
    }

    // Add latency matrix as HTML table if available
    if (latency_matrix_.has_value()) {
        const auto& matrix = latency_matrix_.value();
        size_t n = matrix.num_nodes();

        oss << "\n    // Latency Matrix\n";
        oss << "    latency_matrix [shape=none, margin=0, label=<\n";
        oss << "        <TABLE BORDER=\"1\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"4\">\n";

        // Title row
        oss << "        <TR><TD COLSPAN=\"" << (n + 1) << "\" BGCOLOR=\"lightblue\">"
            << "<B>Latency Matrix (ns)</B></TD></TR>\n";

        // Header row
        oss << "        <TR><TD BGCOLOR=\"lightgray\"></TD>";
        for (size_t j = 0; j < n; ++j) {
            oss << "<TD BGCOLOR=\"lightgray\"><B>P" << j << "</B></TD>";
        }
        oss << "</TR>\n";

        // Data rows
        for (size_t i = 0; i < n; ++i) {
            oss << "        <TR><TD BGCOLOR=\"lightgray\"><B>P" << i << "</B></TD>";
            for (size_t j = 0; j < n; ++j) {
                uint64_t latency = static_cast<uint64_t>(matrix.distance(i, j));
                if (i == j) {
                    oss << "<TD BGCOLOR=\"#e0e0e0\">-</TD>";
                } else {
                    oss << "<TD>" << latency << "</TD>";
                }
            }
            oss << "</TR>\n";
        }

        oss << "        </TABLE>\n";
        oss << "    >];\n";
    }

    oss << "}\n";
    return oss.str();
}

std::string TopologyGraph::to_json() const {
    std::ostringstream oss;

    oss << "{\n";

    // Physical nodes
    oss << "  \"physical_nodes\": [\n";
    for (size_t i = 0; i < physical_nodes_.size(); ++i) {
        const auto& node = physical_nodes_[i];
        oss << "    {\"node_id\": " << node.node_id
            << ", \"tier\": " << node.tier
            << ", \"cluster_id\": " << node.cluster_id
            << ", \"type\": \"" << to_string(node.type) << "\"";
        if (!node.hostname.empty()) {
            oss << ", \"hostname\": \"" << node.hostname << "\"";
        }
        oss << "}";
        if (i < physical_nodes_.size() - 1) oss << ",";
        oss << "\n";
    }
    oss << "  ],\n";

    // Hidden nodes
    oss << "  \"hidden_nodes\": [\n";
    for (size_t i = 0; i < hidden_nodes_.size(); ++i) {
        const auto& node = hidden_nodes_[i];
        oss << "    {\"hv_id\": " << node.hv_id
            << ", \"tier\": " << node.tier
            << ", \"type\": \"" << to_string(node.type) << "\""
            << ", \"label\": \"" << node.inferred_label << "\""
            << ", \"confidence\": " << std::fixed << std::setprecision(2)
            << node.confidence << "}";
        if (i < hidden_nodes_.size() - 1) oss << ",";
        oss << "\n";
    }
    oss << "  ],\n";

    // Edges
    oss << "  \"edges\": [\n";
    for (size_t i = 0; i < edges_.size(); ++i) {
        const auto& edge = edges_[i];
        oss << "    {\"src_id\": " << edge.src_id
            << ", \"dst_id\": " << edge.dst_id
            << ", \"src_is_hidden\": " << (edge.src_is_hidden ? "true" : "false")
            << ", \"dst_is_hidden\": " << (edge.dst_is_hidden ? "true" : "false")
            << ", \"latency_ns\": " << edge.latency_ns
            << ", \"bandwidth_gbps\": " << std::fixed << std::setprecision(1)
            << edge.bandwidth_gbps
            << ", \"type\": \"" << to_string(edge.type) << "\"}";
        if (i < edges_.size() - 1) oss << ",";
        oss << "\n";
    }
    oss << "  ]\n";

    oss << "}\n";
    return oss.str();
}

bool TopologyGraph::write_dot_file(const std::string& output_path) const {
    std::ofstream file(output_path);
    if (!file.is_open()) {
        std::cerr << "Error: Cannot open file for writing: " << output_path << "\n";
        return false;
    }

    file << to_dot();
    return file.good();
}

bool TopologyGraph::render_to_file(const std::string& output_path,
                                    const std::string& layout) const {
    // Determine output format from file extension
    std::string format = "png";  // Default
    size_t dot_pos = output_path.rfind('.');
    if (dot_pos != std::string::npos) {
        format = output_path.substr(dot_pos + 1);
    }

    // Supported formats
    if (format != "png" && format != "svg" && format != "pdf" &&
        format != "jpg" && format != "gif" && format != "ps") {
        std::cerr << "Warning: Unknown format '" << format << "', using PNG\n";
        format = "png";
    }

    // Build GraphViz command
    // Use popen to pipe DOT content directly to graphviz
    std::string command = layout + " -T" + format + " -o \"" + output_path + "\"";

    FILE* pipe = popen(command.c_str(), "w");
    if (!pipe) {
        std::cerr << "Error: Failed to execute GraphViz command: " << command << "\n";
        std::cerr << "Make sure GraphViz is installed (apt install graphviz)\n";
        return false;
    }

    // Write DOT content to pipe
    std::string dot_content = to_dot();
    size_t written = fwrite(dot_content.c_str(), 1, dot_content.size(), pipe);

    int result = pclose(pipe);

    if (written != dot_content.size()) {
        std::cerr << "Error: Failed to write DOT content to GraphViz\n";
        return false;
    }

    if (result != 0) {
        std::cerr << "Error: GraphViz returned error code " << result << "\n";
        return false;
    }

    return true;
}

} // namespace nixl_topo
