#include "topology_graph.hpp"

#include <sstream>
#include <map>
#include <iomanip>

namespace nixl_topo {

void TopologyGraph::add_physical_node(const PhysicalNode& node) {
    physical_nodes_.push_back(node);
}

void TopologyGraph::add_hidden_node(const HiddenNode& node) {
    hidden_nodes_.push_back(node);
}

void TopologyGraph::add_edge(const Edge& edge) {
    edges_.push_back(edge);
}

std::string TopologyGraph::to_adjacency_list() const {
    std::ostringstream oss;

    // Header
    oss << "# Topology Graph - Adjacency List Format\n";
    oss << "# Generated by nixl-topo-disc topology discovery\n";
    oss << "# Format: NODE_ID [PROPERTIES] -> NEIGHBOR_ID [EDGE_PROPERTIES], ...\n\n";

    // Build adjacency map: node_id -> list of (neighbor_id, edge)
    std::map<std::string, std::vector<std::pair<std::string, const Edge*>>> adjacency;

    for (const auto& edge : edges_) {
        std::string src = edge.src_is_hidden
            ? "H" + std::to_string(edge.src_id)
            : "P" + std::to_string(edge.src_id);
        std::string dst = edge.dst_is_hidden
            ? "H" + std::to_string(edge.dst_id)
            : "P" + std::to_string(edge.dst_id);
        adjacency[src].push_back({dst, &edge});
    }

    // Output physical nodes
    oss << "# Physical Nodes\n";
    for (const auto& node : physical_nodes_) {
        std::string node_id = "P" + std::to_string(node.node_id);
        oss << node_id << " [tier=" << node.tier
            << ", cluster=" << node.cluster_id
            << ", type=" << to_string(node.type);
        if (!node.hostname.empty()) {
            oss << ", hostname=" << node.hostname;
        }
        oss << "]";

        auto it = adjacency.find(node_id);
        if (it != adjacency.end() && !it->second.empty()) {
            oss << " -> ";
            for (size_t i = 0; i < it->second.size(); ++i) {
                if (i > 0) oss << ", ";
                const auto& [dst, edge] = it->second[i];
                oss << dst << " [latency_ns=" << edge->latency_ns;
                if (edge->bandwidth_gbps > 0) {
                    oss << ", bw_gbps=" << std::fixed << std::setprecision(1)
                        << edge->bandwidth_gbps;
                }
                oss << "]";
            }
        }
        oss << "\n";
    }

    // Output hidden nodes
    if (!hidden_nodes_.empty()) {
        oss << "\n# Hidden Nodes\n";
        for (const auto& node : hidden_nodes_) {
            std::string node_id = "H" + std::to_string(node.hv_id);
            oss << node_id << " [tier=" << node.tier
                << ", type=" << to_string(node.type);
            if (!node.inferred_label.empty()) {
                oss << ", label=\"" << node.inferred_label << "\"";
            }
            oss << ", confidence=" << std::fixed << std::setprecision(2)
                << node.confidence << "]";

            auto it = adjacency.find(node_id);
            if (it != adjacency.end() && !it->second.empty()) {
                oss << " -> ";
                for (size_t i = 0; i < it->second.size(); ++i) {
                    if (i > 0) oss << ", ";
                    const auto& [dst, edge] = it->second[i];
                    oss << dst << " [latency_ns=" << edge->latency_ns;
                    if (edge->bandwidth_gbps > 0) {
                        oss << ", bw_gbps=" << std::fixed << std::setprecision(1)
                            << edge->bandwidth_gbps;
                    }
                    oss << "]";
                }
            }
            oss << "\n";
        }
    }

    return oss.str();
}

std::string TopologyGraph::to_dot() const {
    std::ostringstream oss;

    oss << "digraph topology {\n";
    oss << "    rankdir=TB;\n";
    oss << "    node [fontname=\"Helvetica\"];\n";
    oss << "    edge [fontname=\"Helvetica\", fontsize=10];\n\n";

    // Define physical nodes (boxes)
    oss << "    // Physical Nodes\n";
    for (const auto& node : physical_nodes_) {
        oss << "    P" << node.node_id << " [shape=box, label=\""
            << "P" << node.node_id;
        if (!node.hostname.empty()) {
            oss << "\\n" << node.hostname;
        }
        oss << "\\nTier " << node.tier << "\"];\n";
    }

    // Define hidden nodes (diamonds)
    if (!hidden_nodes_.empty()) {
        oss << "\n    // Hidden Nodes\n";
        for (const auto& node : hidden_nodes_) {
            oss << "    H" << node.hv_id << " [shape=diamond, style=filled, "
                << "fillcolor=lightgray, label=\"";
            if (!node.inferred_label.empty()) {
                oss << node.inferred_label;
            } else {
                oss << to_string(node.type) << "-" << node.hv_id;
            }
            oss << "\\nTier " << node.tier << "\"];\n";
        }
    }

    // Define edges
    oss << "\n    // Edges\n";
    for (const auto& edge : edges_) {
        std::string src = edge.src_is_hidden
            ? "H" + std::to_string(edge.src_id)
            : "P" + std::to_string(edge.src_id);
        std::string dst = edge.dst_is_hidden
            ? "H" + std::to_string(edge.dst_id)
            : "P" + std::to_string(edge.dst_id);

        oss << "    " << src << " -> " << dst << " [label=\""
            << edge.latency_ns << "ns\"];\n";
    }

    oss << "}\n";
    return oss.str();
}

std::string TopologyGraph::to_json() const {
    std::ostringstream oss;

    oss << "{\n";

    // Physical nodes
    oss << "  \"physical_nodes\": [\n";
    for (size_t i = 0; i < physical_nodes_.size(); ++i) {
        const auto& node = physical_nodes_[i];
        oss << "    {\"node_id\": " << node.node_id
            << ", \"tier\": " << node.tier
            << ", \"cluster_id\": " << node.cluster_id
            << ", \"type\": \"" << to_string(node.type) << "\"";
        if (!node.hostname.empty()) {
            oss << ", \"hostname\": \"" << node.hostname << "\"";
        }
        oss << "}";
        if (i < physical_nodes_.size() - 1) oss << ",";
        oss << "\n";
    }
    oss << "  ],\n";

    // Hidden nodes
    oss << "  \"hidden_nodes\": [\n";
    for (size_t i = 0; i < hidden_nodes_.size(); ++i) {
        const auto& node = hidden_nodes_[i];
        oss << "    {\"hv_id\": " << node.hv_id
            << ", \"tier\": " << node.tier
            << ", \"type\": \"" << to_string(node.type) << "\""
            << ", \"label\": \"" << node.inferred_label << "\""
            << ", \"confidence\": " << std::fixed << std::setprecision(2)
            << node.confidence << "}";
        if (i < hidden_nodes_.size() - 1) oss << ",";
        oss << "\n";
    }
    oss << "  ],\n";

    // Edges
    oss << "  \"edges\": [\n";
    for (size_t i = 0; i < edges_.size(); ++i) {
        const auto& edge = edges_[i];
        oss << "    {\"src_id\": " << edge.src_id
            << ", \"dst_id\": " << edge.dst_id
            << ", \"src_is_hidden\": " << (edge.src_is_hidden ? "true" : "false")
            << ", \"dst_is_hidden\": " << (edge.dst_is_hidden ? "true" : "false")
            << ", \"latency_ns\": " << edge.latency_ns
            << ", \"bandwidth_gbps\": " << std::fixed << std::setprecision(1)
            << edge.bandwidth_gbps
            << ", \"type\": \"" << to_string(edge.type) << "\"}";
        if (i < edges_.size() - 1) oss << ",";
        oss << "\n";
    }
    oss << "  ]\n";

    oss << "}\n";
    return oss.str();
}

} // namespace nixl_topo
